# Generated by Django 4.1.3 on 2022-12-11 01:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uids', shortuuidfield.fields.ShortUUIDField(blank=True, default='jco7iNwWWsLZxhyKfoG9CC', editable=False, max_length=22, verbose_name='UIDS')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email-Adress')),
                ('password', models.CharField(max_length=150, verbose_name='Password')),
                ('date_joinded', models.DateTimeField(auto_now_add=True, verbose_name='Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.BooleanField(default=False)),
                ('free_trial', models.BooleanField(default=False)),
                ('trial_start_date', models.DateTimeField(auto_now_add=True)),
                ('subscription_expired', models.DateTimeField(default=datetime.datetime(2022, 12, 11, 1, 12, 34, 438205, tzinfo=datetime.timezone.utc), verbose_name='Subscription expiration')),
                ('free_trial_expired', models.DateTimeField(default=datetime.datetime(2022, 12, 11, 1, 12, 34, 438205, tzinfo=datetime.timezone.utc), verbose_name='Free trial expiration')),
                ('time_remaining', models.DurationField(verbose_name='Time remaining')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='Subject')),
                ('opinion', models.TextField(max_length=500, verbose_name='Opinion')),
                ('date_writing', models.DateTimeField(auto_now_add=True, verbose_name='Writing in')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
