# Generated by Django 4.1.3 on 2022-12-11 01:18

import datetime
from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uids',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='P4QfpWfqwERj2cWLM9m3fQ', editable=False, max_length=22, verbose_name='UIDS'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='free_trial_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 1, 18, 42, 320642, tzinfo=datetime.timezone.utc), verbose_name='Free trial expiration'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 1, 18, 42, 320642, tzinfo=datetime.timezone.utc), verbose_name='Subscription expiration'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='time_remaining',
            field=models.DurationField(null=True, verbose_name='Time remaining'),
        ),
    ]
