# Generated by Django 4.1.3 on 2022-12-11 01:44

import datetime
from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_usersubscription_time_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='time_remaining',
            field=models.DurationField(default=datetime.timedelta(days=7), verbose_name='Time remaining'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uids',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default='iYt5RwDtHiCPPhihTomKaP', editable=False, max_length=22, verbose_name='UIDS'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='free_trial_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 1, 44, 10, 542727, tzinfo=datetime.timezone.utc), verbose_name='Free trial expiration'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 1, 44, 10, 542727, tzinfo=datetime.timezone.utc), verbose_name='Subscription expiration'),
        ),
    ]
